# Generated by Django 4.2.5 on 2023-10-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='points',
            field=models.BooleanField(default=False, verbose_name='правильность ответа'),
        ),
    ]
